error-tags:
  RD:
    packages:
      - com.exasol.releasedroid.main
      - com.exasol.releasedroid.usecases.request
      - com.exasol.releasedroid.usecases.release
      - com.exasol.releasedroid.usecases.report
      - com.exasol.releasedroid.output
    highest-index: 21
  RD-VAL:
    packages:
      - com.exasol.releasedroid.usecases.validate
    highest-index: 21
  RD-REP:
    packages:
      - com.exasol.releasedroid.usecases.repository
      - com.exasol.releasedroid.adapter.repository
      - com.exasol.releasedroid.adapter
    highest-index: 31
  RD-GH:
    packages:
      - com.exasol.releasedroid.adapter.github
    highest-index: 29
  RD-CP:
    packages:
      - com.exasol.releasedroid.adapter.communityportal
    highest-index: 8
  RD-JIRA:
    packages:
      - com.exasol.releasedroid.adapter.jira
    highest-index: 4