error-tags:
  RD:
    packages:
      - com.exasol.releasedroid.main
      - com.exasol.releasedroid.usecases.request
    highest-index: 10
  RD-VAL:
    packages:
      - com.exasol.releasedroid.usecases.validate
    highest-index: 19
  RD-REP:
    packages:
      - com.exasol.releasedroid.adapter
    highest-index: 11
  RD-GH:
    packages:
      - com.exasol.releasedroid.adapter.github
    highest-index: 9