error-tags:
  RD:
    packages:
      - com.exasol.releasedroid.main
      - com.exasol.releasedroid.usecases.request
    highest-index: 10
  RD-VAL:
    packages:
      - com.exasol.releasedroid.usecases.validate
    highest-index: 21
  RD-REP:
    packages:
      - com.exasol.releasedroid.adapter.java
      - com.exasol.releasedroid.adapter.maven
      - com.exasol.releasedroid.adapter.scala
      - com.exasol.releasedroid.adapter
    highest-index: 19
  RD-GH:
    packages:
      - com.exasol.releasedroid.adapter.github
    highest-index: 25
  RD-CP:
    packages:
      - com.exasol.releasedroid.adapter.communityportal
    highest-index: 8